listener 1883 0.0.0.0
allow_anonymous false

auth_plugin /mosquitto/go-auth.so

auth_opt_backends mysql
auth_opt_mysql_host mysql_db
auth_opt_mysql_port 3306
auth_opt_mysql_user root
auth_opt_mysql_password root_password
auth_opt_mysql_dbname mqtt_db

auth_opt_mysql_userquery SELECT password_hash FROM users WHERE username = ?
auth_opt_mysql_aclquery SELECT topic FROM acl WHERE username = ? AND (rw = ? OR rw = 3)

auth_opt_hasher bcrypt
auth_opt_hasher_cost 10
